version: "3"
services:
  tao-tool-kit:
    container_name: tao-tool-kit
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app/src
    working_dir: /app/src
    tty: true
